/*
 * This file is generated by jOOQ.
*/
package sample;


import javax.annotation.Generated;

import sample.tables.Users;


/**
 * Convenience access to all tables in PUBLIC
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.1"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

    /**
     * The table <code>PUBLIC.USERS</code>.
     */
    public static final Users USERS = sample.tables.Users.USERS;
}
