language: java
jdk:
  - oraclejdk8

addons:
  apt:
    packages:
      # Force the installation of latest JDK release
      - oracle-java8-installer

cache:
  directories:
    - '$HOME/.m2/repository'
before_cache:
  # Trick to avoid useless S3 cache updates
  # (force this step to always return 0, as it might fail for some unkown reasons, so far...)
  - mv $HOME/.m2/repository/org/springframework/data/spring-data-jooq /tmp/skip-caching-trick || /bin/true

notifications:
  on_success: change
  on_failure: always
  on_start:   never
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/ffe64732e680e6a415f9

